


name: Java CI with Maven and Semgrep

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  buildMavenWithDepTree:
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: $${ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Build Dependency Tree
      # The mvn command traverses the repository and generates a dependency tree for each pom.xml file
      run: mvn dependency:tree -DoutputFile=maven_dep_tree.txt -Dmaven.test.skip=true

    - name: Create Zip File
      run: find . -type f -name 'maven_dep_tree.txt' -exec zip -r deptree.zip {} +
    - name: Upload Dependency Zip
      uses: actions/upload-artifact@v4
      with:
        name: zipfile
        path: deptree.zip

  semgrep:
    permissions:
      contents: read 
      security-events: write
    needs: buildMavenWithDepTree
    name: Scan
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact from the previous job
        uses: actions/download-artifact@v3
        with:
          name: deptree.zip
      - name: Semgrep Scan
        run: |
          unzip -o deptree.zip
          semgrep ci --sarif --sarif-output=minitest.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: minitest.sarif
        if: always()

